export const GET_BEST_STORIES_REQUEST = 'GET_BEST_STORIES_REQUEST'
export const GET_BEST_STORIES_SUCCESS = 'GET_BEST_STORIES_SUCCESS'
export const GET_BEST_STORIES_ERROR = 'GET_BEST_STORIES_ERROR'

export const GET_STORY_BY_ID_REQUEST = 'GET_STORY_BY_ID_REQUEST'
export const GET_STORY_BY_ID_SUCCESS = 'GET_STORY_BY_ID_SUCCESS'
export const GET_STORY_BY_ID_ERROR = 'GET_STORY_BY_ID_ERROR'
